version: '3'

services:
  app:
    container_name: svelte_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./public:/app/public
    environment:
      DB_URI: mongodb://db:27017
      DB_NAME: "${DB_NAME}"
      JWT_SECRET: "${JWT_SECRET}"
      AUTH_MAX_AGE: "${AUTH_MAX_AGE}"
      BODY_SIZE_LIMIT: "10000000"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - db

  db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
